### PR TITLE
Upgrade license to GPLv3

### PR DESCRIPTION
**Pull request by skangas**
This upgrades the license to GPLv3. Thanks!

### CODE REVIEW

**Comment by wasamasa** [comment]
I'm not even sure whether I'm allowed to accept this. The code is almost entirely the work by the author. There are some other contributions (I added code to handle undo-tree correctly), but I suspect I need to email them about a license change.

**Comment by skangas** [comment]
Relicensing it to the GPLv3 is fine, as the file clearly says:

```
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 2 of
;; the License, or (at your option) any later version.
```

Note the "any later version", which is what allows anyone to relicense it to the GPLv3 without asking for permission. In the future, if there is ever a GPLv4, you can upgrade to that too.

As for why this even matters, see:
https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html
https://www.gnu.org/licenses/rms-why-gplv3.html

I hope that helps!

**Comment by wasamasa** [comment]
Thank you, I forgot about that nuance!

**Comment by skangas** [comment]
Thanks for merging it!

**Pull request merged**
