### PR TITLE
require undo-tree when compile

### PR DESCRIPTION
**Pull request by thanhvg**
Otherwise I get an error about `undo-tree-node-p` not found when canary found... 

Thanks

### CODE REVIEW

**Comment by wasamasa** [comment]
You'll have to be more clear than that: Under which circumstances does the code give you problems? What exactly did you do to run into errors?

**Comment by thanhvg** [comment]
Well my emacs (spacemacs) runs on byte complied elc files not el files. The compiled elc is not aware of `undo-tree-node-p` in my case. 

How to reproduce:
- open scratch buffer.
- type: some lines of text 
- move cursor away, then `g;`  cursor jumps back to last edited position. It works because `undo-tree-node-p` isn't triggered yet.
- now do the same as above, this time `undo-tree-node-p` will be called inside `goto-last-change` so I get the error `undo-tree-node-p not found`

If I open `goto-chg.el` and `eval` it the problem is gone. So I guess this is the compilation problem and to be frank my solution is what google told me so it may not be correct but it fixed my use case.

Thanks

**Comment by wasamasa** [comment]
Sorry, but I do not support Spacemacs. If you can reproduce this without Spacemacs from a clean install, then I'll further investigate. Who knows, maybe you didn't manage to update the package cleanly and the issue is gone afterwards.

**Comment by thanhvg** [comment]
Fair enough, I understand `spacemacs` is not supported however I am not sure `declare-function` can work on macro. When I run `check-declare-file` on goto-chg.el I get these warnings:

````
goto-chg.el:236:Warning (check-declare): said ‘undo-tree-current’ was defined
    in ../undo-tree-0.7.5/undo-tree.el: function not found
goto-chg.el:237:Warning (check-declare): said ‘undo-tree-node-p’ was defined
    in ../undo-tree-0.7.5/undo-tree.el: function not found
goto-chg.el:238:Warning (check-declare): said ‘undo-tree-node-previous’ was
    defined in ../undo-tree-0.7.5/undo-tree.el: function not found
goto-chg.el:239:Warning (check-declare): said ‘undo-tree-node-undo’ was
    defined in ../undo-tree-0.7.5/undo-tree.el: function not found
````

They are mostly macros. 

And the doc https://www.gnu.org/software/emacs/manual/html_node/elisp/Eval-During-Compile.html says when you need foreign macros, use `eval-when-compile`.

Thanks

**Comment by leungbk** [comment]
> Fair enough, I understand `spacemacs` is not supported however I am not sure `declare-function` can work on macro. When I run `check-declare-file` on goto-chg.el I get these warnings:
> 
> ```
> goto-chg.el:236:Warning (check-declare): said ‘undo-tree-current’ was defined
>     in ../undo-tree-0.7.5/undo-tree.el: function not found
> goto-chg.el:237:Warning (check-declare): said ‘undo-tree-node-p’ was defined
>     in ../undo-tree-0.7.5/undo-tree.el: function not found
> goto-chg.el:238:Warning (check-declare): said ‘undo-tree-node-previous’ was
>     defined in ../undo-tree-0.7.5/undo-tree.el: function not found
> goto-chg.el:239:Warning (check-declare): said ‘undo-tree-node-undo’ was
>     defined in ../undo-tree-0.7.5/undo-tree.el: function not found
> ```
> 
> They are mostly macros.
> 
> And the doc https://www.gnu.org/software/emacs/manual/html_node/elisp/Eval-During-Compile.html says when you need foreign macros, use `eval-when-compile`.
> 
> Thanks

Can you try this branch: https://github.com/emacs-evil/goto-chg/pull/10 and see if it works for you? I used `declare-function` without any additional `require` of `undo-tree`, which may not be enough.

If my solution doesn't work, we might have to go with something like what you have. I think `eval-and-compile` makes more sense than `eval-when-compile` here since one of the `undo-tree` forms is a function. I'm not sure how to guarantee that `undo-tree` is compiled at the right time though since we're not putting it in a Package-Requires header.

**Comment by thomasf** [comment]
I have the same issue, no spacemacs and it shoudn't matter since it seems to be a byte compilation/macro issue.  I also byte compile everything, all packages, all of my ~/.emacs.d

**Comment by thomasf** [comment]
I can't seems to get this to work however i arrange my loading..

Even when I explicitly add something that  loads undo-tree before goto-chg when compiling I still get the same `undo-tree-node-p` error after recompiling init.el and restarting emacs even though undo-tree-mode is enabled.

```el

;;;; goto-chg
(eval-when-compile
      (use-package undo-tree
        :ensure t))

(use-package goto-chg
  :ensure t
  :if (not noninteractive)
  :commands (goto-last-change goto-last-change-flash)
  :bind ("C-c C-SPC" . goto-last-change-flash)
  :config
  (progn
    (defun goto-last-change-flash ()
      (interactive)
      (call-interactively 'goto-last-change)
      (nav-flash-show-maybe t))))
```

It does not seem to help even if I remove the goto-chg package from my system and reinstall it, it doesn't seem to be aware of undo-tree even if it is loaded when compiling.

**Comment by thomasf** [comment]
would it be possible to revert https://github.com/emacs-evil/goto-chg/commit/5c057c8623abadf7fd57ce625843435d231f2739 until this issue is resolved?

**Comment by thomasf** [comment]
I forgot that I don't install packages in compile mode so this seems to at least work for my particular setup.  

```
(use-package undo-tree
  :ensure t
  :if (not noninteractive))

(use-package goto-chg
  :ensure t
  :if (not noninteractive)
  :commands (goto-last-change goto-last-change-flash)
  :bind ("C-c C-SPC" . goto-last-change-flash)
 ...
```

**Comment by thomasf** [comment]
The best alternative would maybe be to create another package for goto-chg-undo-tree which actually does depend on undo-tree so that it is always available and installed before goto-chg. It would probably at least be the most user friendly solution.

**Comment by thanhvg** [comment]
@leungbk thank for your help. I don't have time to check our pr now but from reading it I don't think it will solve my problem. I have `undo-tree` already and I want `goto-chg` to just work when byte compiled. 

@thomasf if you can provide a minimal vanilla setup that can prove this bug then the maintainer will be willing to help all of us :). I want to but I am on `spacemacs` and I would rather patch `goto-chg` myself than setting emacs from scratch.

Thanks

**Comment by leungbk** [comment]
@thanhvg I've had byte-compilation issues like yours before. M-x
check-declare-file now gives no warnings with my patch.

**Comment by thomasf** [comment]
> @thanhvg I've had byte-compilation issues like yours before. M-x check-declare-file now gives no warnings with my patch.
> […](#)

I don't think it will work if goto-chg is installed before undo-tree from in an emacs from scratch scenario. Emacs l won't byte compile the marco from undo-tree into goto-chg.elc which is the root of this problem.

putting  `(require 'undo-tree nil t)` at the root level of the file will at least work when undo-tree already is installed before goto-chg. This can probably be wrapped inside an `eval-when-compile` to avoid loading undo-tree at run time if the user don't use it even if it is installed.

**Comment by leungbk** [comment]
> @leungbk thank for your help. I don't have time to check our pr now but from reading it I don't think it will solve my problem.

> I don't think it will work if goto-chg is installed before undo-tree from in an emacs from scratch scenario. Emacs l won't byte compile the marco from undo-tree into goto-chg.elc which is the root of this problem.

I expanded the macro myself in the patch. Please test.

I tested by byte-compiling my patched `goto-chg`, exiting Emacs, then opening Emacs and evaluating `undo-tree.el` and turning on `global-undo-tree-mode`. I did not observe any `undefined function` errors after doing this.

**Comment by wasamasa** [comment]
Closing this in favor of #10.

**Pull request closed without merging**
